name: cljstyle

on:
  push:
  workflow_dispatch:

jobs:
  cljstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: latest

    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: ${{ runner.os }}-cljstyle-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-cljstyle-

    - name: Run cljstyle check
      run: clojure -M:cljstyle check