name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Prepare java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: latest

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.cljs/.aot_cache
        key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Run tests
      run: clojure -M:test --reporter documentation